# Generated by Django 2.1.5 on 2021-07-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210629_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='descicao',
            new_name='descricao',
        ),
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
